apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nginx-exporter
  namespace: demo
  labels:
    release: monitoring  # must match your Prometheus release name
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: prometheus-nginx-exporter
  namespaceSelector:
    matchNames:
      - demo
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
